spring:
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      allow-override: true
      override-none: true

management.security.enabled: false
management.endpoints.web.exposure.include: "*"

spring.cloud.refresh.refreshable: false

logging.level.org.springframework: INFO
